### ISSUE TITLE
Duplicate names in getFE if FEs have same factor levels

### ISSUE THREAD

**Issue by zauster** [amrei-stammann/alpaca#4]
Hey, if you have e.g. two fixed effects with the same factor levels (such as the countries in the empirical example) then the function `getFEs` returns a named vector with duplicated names. 
Then it is impossible to extract a certain FE by name (it is still possible to do by index, but a bit cumbersome), as you will always get the (I think) first matching name.

Perhaps it would be better to return a list of named vectors? That would also make the FEs easier to handle as I don't have to keep track of the number of the FEs.

**Comment by amrei-stammann** [comment]
Consider the trade example from the vignette:

mod1 <- feglm(exp1to2 ~ custrict11 + ldist + comlang + border + regional + comcol + curcol +
                colony + comctry | exp.time + imp.time,
              cudata[exp1to2 > 0.0], family = poisson())
alpha <- getFEs(mod1)

If you want to extract a certain fixed effect by name you can simply use 

alpha[names(alpha) == "111.1948"]

where the first number refers to the first category (exp.time) and the second number to the second category (imp.time).

You can also split the vector of fixed effects by each category and match by name

alpha_exp_time <- alpha[seq(mod1$lvls.k[[1L]])]
alpha_imp_time <- alpha[- seq(mod1$lvls.k[[1L]])]
alpha_exp_time[names(alpha_exp_time) == "111.1948"]
alpha_imp_time[names(alpha_imp_time) == "111.1948"]

But to return a list of named vectors might be more convenient. We will change this in the next update.
