### ISSUE TITLE
'conv' not found

### ISSUE THREAD

**Issue by zauster** [amrei-stammann/alpaca#5]
Hey,
with the new alpaca 0.3 there is an error if the estimation does not converge in `iter.max` iterations.
Try this e.g. with the examples in the vignettes but set the max iterations to 1:
```
control = list(iter.max = 1)
```
The object `conv` seems only to be set when the algorithm converges.

**Comment by amrei-stammann** [comment]
Thanks for the report. Will be fixed during the next week.
