### ISSUE TITLE
just cosmetics

### ISSUE THREAD

**Issue by zauster** [amrei-stammann/alpaca#6]
The last line of output of `summary.feglm` does not end with a newline, so the next command will be placed in the same line. But that's subjective...

```
> summary(stat)
binomial - probit link

LFP ~ KID1 + KID2 + KID3 + log(INCH) | ID + TIME

Estimates:
          Estimate Std. error z value            Pr(> |z|)    
KID1      -0.67690    0.05630   -12.0 < 0.0000000000000002 ***
KID2      -0.34438    0.04990    -6.9      0.0000000000051 ***
KID3      -0.00704    0.03534    -0.2                 0.84    
log(INCH) -0.23414    0.05440    -4.3      0.0000167933183 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

residual deviance= 6070,
null deviance= 8152,
n= 5976, l= [664, 9]

( 7173 observation(s) deleted due to perfect classification )

Number of Fisher Scoring Iterations: 6> ls()
```

In the vignette, instead of `cudata <- as.data.table(cudata)` you could use `setDT(cudata)` as this avoids copying the object. But again, this is subjective.

**Comment by zauster** [comment]
Thanks a lot for your work and the `getFEs` function, makes my work again easier!

**Comment by amrei-stammann** [comment]
Again thanks for your suggestions. Will be incorporated in the next update.
