### ISSUE TITLE
Output to latex

### ISSUE THREAD

**Issue by leonardodamico** [amrei-stammann/alpaca#8]
Hi! First of all, congratulations on doing this package, it is fast and simplifies a lot of issues! We have a big dataset on which we are fitting a Poisson regression with many levels of FE and we really appreciate alpaca! 

Thanks a lot for all your work!

I was wondering whether it is possible to transform the feglm in a felm/lm-like object that is interpretable by stargazer/xtable in order to output it to Latex. I know this is minor but I was wondering if it is something you are planning to introduce! 

Thanks again!

**Comment by amrei-stammann** [comment]
This is a good idea, but compatibility with stargazer can only be activated by the maintainer of stargazer.

However you can directly use xtable:

```
# Generate an artificial data set for logit models
library(alpaca)
data <- simGLM(100L, 10L, 1805L, model = "logit")

# Fit 'feglm()'
mod <- feglm(y ~ x1 + x2 + x3 | i + t, data)
summary(mod)

# Latex Output
library(xtable)
xtable(coef(summary(mod)))
```

Best, 
Amrei

**Comment by leonardodamico** [comment]
Thank you amrei! 

Best,
Leonardo

**Comment by zauster** [comment]
Just FYI: The texreg package can also deal with `feglm` objects and display several models beside each other...
